### ISSUE TITLE
转盘转的过程中，点击其他按钮的问题

### ISSUE THREAD

**Issue by MikasaAckerman** [MatChat-Inc/UsenGame-Roulette#11]
转盘转的过程中，音乐播放
此时点击其他按钮，音乐还是播放
看看是改成转的时候其他按钮不能点击方便，还是点击其他按钮关闭音乐方便

另外，随机和自选情况下，红蓝按钮的bug（转盘转不转的时候都一样）
随机
1. 点击红按钮变其他转盘的时候，有背景但是分类也是只有个框，点击返回有时变黑背景有时变白背景
2. 点蓝色按钮选其他分类的时候，也是回到首页，有背景但是分类也是只有个框
3. 以上两点，按返回都能再返回个首页，但是再进去转盘的时候，红蓝按钮就点不动了

自选
1. 红按钮没问题
2. 点蓝色按钮选其他分类的时候，回到首页，有背景但是分类也是只有个框，和上面一样
3. 再进去转盘的时候，红蓝按钮没问题

**Comment by MikasaAckerman** [comment]
有视频，但是文件太大上传不了，怎么共享比较方便。。？

**Comment by 949886** [comment]
国内百度云、夸克比较好，日本那边速度就不确定了，Onedrive 也行

**Comment by 949886** [comment]
Done. 

原因：随机流程改了，跳转逻辑发生了错误。

@MikasaAckerman 
顺便一提，多个 bug 最好分成多个 issue 来写，不然不好跟踪，比如这个就可以分成 音乐播放 bug 和 按钮bug 来处理。
