### ISSUE TITLE
转盘Start页面，按蓝色按钮，一直按一直按，到最后会出问题。。Unity模拟器运行一下便知

### ISSUE THREAD

**Issue by MikasaAckerman** [MatChat-Inc/UsenGame-Roulette#14]
就选第一个大分类，点到转盘Start页面，一直按蓝色按钮
后面是编辑页面变成默认值，再蓝色到转盘是空的，这在使用上是有问题的
好像是在编辑保存的时候没保存到original里，但是选择的分类变成了original，就是空的了

**Comment by 949886** [comment]
Done
