### ISSUE TITLE
转盘背景色变回去了😂

### ISSUE THREAD

**Issue by MikasaAckerman** [MatChat-Inc/UsenGame-Roulette#18]
![Image](https://github.com/user-attachments/assets/1996b8e3-e248-49e9-9a79-fac0422c5663)
![Image](https://github.com/user-attachments/assets/5719ad89-a76c-49fb-937a-dd7da29b997b)

**Comment by 949886** [comment]
Done.

创建转盘的色彩没更新，现在创建的新转盘颜色都是正常的了，以前创建的颜色不会变。
