### ISSUE TITLE
接口来了！

### ISSUE THREAD

**Issue by MikasaAckerman** [MatChat-Inc/UsenGame-Roulette#19]
式样书 [ルーレット_API仕様書.xlsx](https://github.com/MatChat-Inc/UsenMiniGames/blob/main/Documentation/03_%E3%83%AB%E3%83%BC%E3%83%AC%E3%83%83%E3%83%88/%E3%83%AB%E3%83%BC%E3%83%AC%E3%83%83%E3%83%88_API%E4%BB%95%E6%A7%98%E6%9B%B8.xlsx)

・测试环境地址
https://api-stg.tvsignage.usen.com/
・正式环境地址
https://api.tvsignage.usen.com/

postman测试Header
x-umid：01HA1S5FCXKDB78KGBZ0QP3HYQ
unisCustomerCd: 750900428
neosContractCd：N00000000000000065760

其中
x-umid：ssid
unisCustomerCd: 固定E6kbsBYhQgNEwT8p7bDQT-SVQitzGXmQ
neosContractCd：tvIdentityCd

**Comment by 949886** [comment]
![Image](https://github.com/user-attachments/assets/5a1b149d-01b0-4503-adbf-0a4b3d228ab6)

用测试 Header 出现了 403 错误，是接口有问题还是说是参数问题呢？

**Comment by MikasaAckerman** [comment]
![Image](https://github.com/user-attachments/assets/620079cf-04ef-429b-beb6-9a8fc89fa324)
不会是网络环境问题吧我敲
