### ISSUE TITLE
删除功能修改

### ISSUE THREAD

**Issue by MikasaAckerman** [MatChat-Inc/UsenGame-Roulette#2]
删除功能，删完后，右边转盘也隐藏掉
总之就是转盘列表是空的话，右边不显示转盘（不是删除的情况也会出现，应该是删了后退出再进也是这样？）
![Image](https://github.com/user-attachments/assets/e2d16d59-2853-40dc-8aad-cd8f32a2582a)

**Comment by 949886** [comment]
解决
