### ISSUE TITLE
转盘背景色搞浓一点

### ISSUE THREAD

**Issue by MikasaAckerman** [MatChat-Inc/UsenGame-Roulette#4]

**Comment by MikasaAckerman** [comment]
![Image](https://github.com/user-attachments/assets/d27196aa-cdae-45a3-b828-92a8e221ad8a)
![Image](https://github.com/user-attachments/assets/452eb7b3-0889-41f7-8f13-b34ed2e93077)
有点色差。。不知道是不是电视的问题，总之浓一点

**Comment by 949886** [comment]
Done，目前的转盘颜色预览：

![Image](https://github.com/user-attachments/assets/34f4999a-0a9d-478b-8e8c-d1fa16e853b6)
